### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by kid-three** [skydiver/nextjs-semantic#7]
Brand new installation and one that is about 2 weeks old have issues displaying icons.

Followed README
1. clone repo
2. `npm install`
3. `npm run semantic:build`
4. `npm run dev`

Then just add 
`import {  Icon } from "semantic-ui-react";`

Then on the return

` <Icon name="users" />`

Icon does not show. I tried with many other icons.

**Comment by kid-three** [comment]
Rolling back to commit `85186da1cce4b5b3c756ba9d625fce910cac0daa` solves the issue.

There were a lot of updates in the following 3 commits. I still can't find where things break

**Comment by kid-three** [comment]
Doing some trial and error:

Reverting file loader to 

`"file-loader": "^4.1.0",`

fixes all issues with Icons

**Comment by skydiver** [comment]
nice catch @kid-three 

Thank you
